django web application/youtubeproject/exploration/urls.py
from django.urls import path
from . import views
from exploration.dash_apps.finished_apps import simpleexample

app_name='exploration'

urlpatterns = [
    path('',views.dashboard_view,name='dashboard')
]

django web application/youtubeproject/prediction/urls.py
from django.urls import path
from . import views
from prediction.dash_apps.finished_apps import importance

app_name='prediction'

urlpatterns = [
    path('',views.ml_view,name='ml')
]

django web application/youtubeproject/youtubeproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('exploration/',include('exploration.urls')),
    path('prediction/',include('prediction.urls')),
    path('',RedirectView.as_view(url='exploration/')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),

]

django web application/youtubeproject/exploration/models.py
from django.db import models

# Create your models here.

django web application/youtubeproject/prediction/models.py
from django.db import models

# Create your models here.

Category_Choices = (
    ('Soccer-International','Soccer-International'),
    ('Soccer-Highlights', 'Soccer-Highlights'),
    ('Soccer-LaLiga','Soccer-LaLiga'),
    ('Soccer-SerieA','Soccer-SerieA'),

    ('Basketball-Highlights','Basketball-Highlights'),
    ('Basketball-NBA','Basketball-NBA'),
    ('Basketball-Highlights','Basketball-Highlights'),

    ('Fighting-Highlights','Fighting-Highlights'),
    ('Fighting-UFC','Fighting-UFC'),
    ('Fighting-WWE','Fighting-WWE'),

    ('Racing-Formula 1','Racing-Formula 1'),
    ('Racing-Formula 2','Racing-Formula 2'),
    ('Racing-MotoGP','Racing-MotoGP'),
    ('Racing-Highlights','Racing-Highlights'),
    ('Racing-Son Viraj','Racing-Son Viraj'),

    ('Betting','Betting'),

    ('Tennis-Highlights','Tennis-Highlights'),
    ('Tennis-Wimbledon','Tennis-Wimbledon'),
    ('Tennis-ATP','Tennis-ATP')
)

Year_Choices = (
    ('2018','2018'),
    ('2019', '2019'),
    ('2020','2020'),
    ('2021','2021'),
    ('2022','2022')
)

class MlModel(models.Model):
    likes = models.IntegerField()
    comments = models.IntegerField()
    duration = models.IntegerField()
    category = models.CharField(max_length=30,choices=Category_Choices, default='Soccer-International')
    year = models.CharField(max_length=5,choices=Year_Choices, default='2022')

django web application/youtubeproject/prediction/forms.py
from django import forms
from . models import MlModel
from django.forms import ModelForm



'''
class MlForm(forms.Form):
    likes = forms.IntegerField(label='like amount')
    comments = forms.IntegerField(label='comment amount')
    category = forms.ChoiceField(label='please select a category',
                                widget=forms.RadioSelect, 
                                choices=CATEGORIES)
'''

class MlForm(ModelForm):
    class Meta:
        model = MlModel
        fields = '__all__'

        widgets = {

            'likes': forms.NumberInput(attrs={'class':'form-control',
                                            'placeholder':'Enter like amount'}),
            'comments': forms.NumberInput(attrs={'class':'form-control',
                                            'placeholder':'Enter comment amount'}),
            'duration': forms.NumberInput(attrs={'class':'form-control',
                                            'placeholder':'Enter duration in seconds'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'year': forms.Select(attrs={'class':'form-control'}),


        }

django web application/youtubeproject/exploration/views.py
from django.shortcuts import render

# Create your views here.

def dashboard_view(request):
    return render(request,'exploration/dashboard.html')

django web application/youtubeproject/prediction/views.py
from django.shortcuts import render
from . forms import MlForm
from joblib import load
import numpy as np
import os

os.chdir(os.path.dirname(os.path.abspath(__file__)))

model_filename = 'mlmodels/model_04-11-22_new_RF.pickle'
scaler_filename = 'mlmodels/scaler_04-11-22.pickle'

model = load(model_filename)
scaler = load(scaler_filename)

def predict_view(likes,comments,duration,category,year):

    z = []

    if category == 'Basketball-Highlights':
        c = [0,0,0,0,0]
        s = [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    elif category == 'Basketball-NBA':
        c = [0,0,0,0,0]
        s = [0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0]
    elif category == 'Basketball-European':
        c = [0,0,0,0,0]
        s = [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

    elif category == 'Soccer-Highlights':
        c = [0,0,0,1,0]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0]
    elif category == 'Soccer-LaLiga':
        c = [0,0,0,1,0]
        s = [0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0]
    elif category == 'Soccer-SerieA':
        c = [0,0,0,1,0]
        s = [0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0]
    elif category == 'Soccer-International':
        c = [0,0,0,1,0]
        s = [0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]

    elif category == 'Fighting-Highlights':
        c = [0,1,0,0,0]
        s = [0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
    elif category == 'Fighting-UFC':
        c = [0,1,0,0,0]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0]
    elif category == 'Fighting-WWE':
        c = [0,1,0,0,0]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0]

    elif category == 'Racing-Formula 1':
        c = [0,0,1,0,0]
        s = [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0]
    elif category == 'Racing-Formula 2':
        c = [0,0,1,0,0]
        s = [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]
    elif category == 'Racing-MotoGP':
        c = [0,0,1,0,0]
        s = [0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0]
    elif category == 'Racing-Highlights':
        c = [0,0,1,0,0]
        s = [0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0]
    elif category == 'Racing-Son Viraj':
        c = [0,0,1,0,0]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0]

    elif category == 'Tennis-Highlights':
        c = [0,0,0,0,1]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]
    elif category == 'Tennis-Wimbledon':
        c = [0,0,0,0,1]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]
    elif category == 'Tennis-ATP':
        c = [0,0,0,0,1]
        s = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]


    elif category == 'Betting':
        c = [0,0,0,0,0]
        s = [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]


    if year == '2018':
        y = [0,0,0,0]
    elif year == '2019':
        y = [1,0,0,0]
    elif year == '2020':
        y = [0,1,0,0]
    elif year == '2021':
        y = [0,0,1,0]
    elif year == '2022':
        y = [0,0,0,1]


    z = [likes,comments,duration] + c + y + s
    z = np.expand_dims(z, axis=0)
    z = scaler.transform(z)
    pred = model.predict(z)

    return pred


def ml_view(request):

	if request.method == "POST":
		form = MlForm(request.POST)

		if form.is_valid():
			form.save()
			result = form.cleaned_data

			likes = result['likes']
			comments = result['comments']
			duration = result['duration']
			category = result['category']
			year = result['year']

			pred = predict_view(likes,comments,duration,category,year)
			pred = round(pred[0])

			return render(request,'prediction/ml.html',context={'form':form,
																'likes':likes,
																'comments':comments,
																'duration':duration,
																'category':category,
																'year':year,
																'pred':pred})
	
	else:
		form = MlForm()
	

	return render(request,'prediction/ml.html',context={'form':form})

django web application/youtubeproject/exploration/templates/exploration/dashboard.html
{% extends 'navbar.html' %}

{% load static %}

{% block content %}

<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
{% load plotly_dash %}



<div class="{% plotly_class name='SimpleExample' %} card" style="height: 100%; width: 100%">

    {% plotly_app name='SimpleExample' ratio=0.65 %}

</div>



{% endblock content %}

django web application/youtubeproject/prediction/templates/prediction/ml.html
{% extends 'navbar.html' %}

{% load static %}



{% block content %}

<link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
<!--
<div class='container'>
    <form method="POST">
    {% csrf_token %}

    {{ form.as_p }}

    <button class='btn btn-secondary'>Predict</button>
</div>
</form>
//-->


<section class="hero is-fullheight">
    <div class="hero-body">
      <div class="container">
        <div class="columns is-centered">
        
          <div class="column is-4-tablet is-4-desktop is-5-widescreen">
            <form method="POST" action="." class="box">
              {% csrf_token %}

              <h1 class="has-text-centered mb-4 is-size-4">Machine Learning Model</h1>

              <div class="field">
                <label for="" class="label">Likes</label>
                <div class="control has-icons-left">
                  {{ form.likes }}
                </div>
              </div>

              <div class="field">
                <label for="" class="label">Comments</label>
                <div class="control has-icons-left">
                  {{ form.comments }}
                </div>
              </div>
              <div class="field">
                <label for="" class="label">Duration</label>
                <div class="control has-icons-left">
                  {{ form.duration }}
                </div>
              </div>
              <div class="field">
                <label for="" class="label">Category</label>
                <div class="control has-icons-left">
                  {{ form.category }}
                </div>
              </div>
              <div class="field">
                <label for="" class="label">Year</label>
                <div class="control has-icons-left">
                  {{ form.year }}
                </div>
              </div>


              <div class="field">
                <button class="button is-success" type="submit">
                  Predict
                </button>
              </div>
              <div class="field">
                Predcited View Amount is {{pred}}
              </div>
            </form>
            
          </div>
        </div>
      </div>
    </div>
  </section>

{% load plotly_dash %}

<div class="{% plotly_class name='Importance' %} card" style="height: 100%; width: 100%">

  {% plotly_app name='Importance' ratio=0.65 %}

</div>

{% endblock content %}

django web application/youtubeproject/templates/navbar.html
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <style>
      *{
        font-family: 'Quicksand', sans-serif; 
      }
    </style>
  </head>
  <body>
    {% load static %}
    <nav class="navbar is-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://www.youtube.com/c/ssport">
          <img src="{% static 'img/icon.png' %}" width="30px" height="200px">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
          <a class="navbar-item" href="{% url 'exploration:dashboard' %}">
            Exploration
          </a>
        
          <a class="navbar-item" href="{% url 'prediction:ml' %}">
            Prediction
          </a>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">     
            <a class="navbar-item" href="https://www.youtube.com/c/ssport">
              <img src="{% static 'img/github.png' %}" width="50px" height="200px">
            </a>
            <a class="navbar-item" href="https://www.youtube.com/c/ssport">
              <img src="{% static 'img/link.png' %}" width="50px" height="200px">
            </a>
            
          </div>
        </div>
      </div>
      </nav>
  </body>
</html>












<!--
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>

</head>
-->
<!--
<body>
{% load static %}
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="https://www.youtube.com/c/ssport">
            <img src="{% static 'img/icon.png' %}" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
            S Sport
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'exploration:dashboard' %}">Exploration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'prediction:ml' %}">Prediction</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

--> 

<!--Above--> 

    {% block content %}
    
    
    {% endblock  %}
    
<!--Below--> 











<!--

</body>
</html>

--> 